version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'chalk'
      - dependency-name: 'chart.js'
      - dependency-name: 'compare-versions'
      - dependency-name: 'concurrently'
      - dependency-name: 'got'
      - dependency-name: 'helmet'
      - dependency-name: 'supertest'
      - dependency-name: 'swagger-ui-express'
      - dependency-name: 'swiper'
